import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :archive_classifier, ArchiveClassifierWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :archive_classifier, ArchiveClassifierWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Do not print debug messages in production
config :logger, level: :info

# Whisper ML serving — disabled by default in prod, enable via env var
config :archive_classifier, start_whisper: false
config :archive_classifier, start_twerker: false
config :archive_classifier, whisper_model: "openai/whisper-small"

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
